[versions]
agp = "8.9.0"
kotlin = "2.0.20"
junit = "4.13.2"

[libraries]
testing-junit = { group = "junit", name = "junit", version.ref = "junit" }


[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
